In [1]:
import pandas as pd

In [2]:
# Load the Kenya Food Price dataset from the CSV file 
data = pd.read_csv(f"Kenya_Food_Price.csv")

# Display the first few riws to verify taht the data loaded correctly
print(data.head())

        date   admin1   admin2   market  market_id  latitude  longitude  \
0  1/15/2006    Coast  Mombasa  Mombasa        191     -4.05      39.67
1  1/15/2006    Coast  Mombasa  Mombasa        191     -4.05      39.67
2  1/15/2006    Coast  Mombasa  Mombasa        191     -4.05      39.67
3  1/15/2006    Coast  Mombasa  Mombasa        191     -4.05      39.67
4  1/15/2006  Eastern    Kitui    Kitui        187     -1.37      38.02

             category      commodity  commodity_id   unit priceflag  \
0  cereals and tubers          Maize            51     KG    actual
1  cereals and tubers  Maize (white)            67  90 KG    actual
2     pulses and nuts          Beans            50     KG    actual
3     pulses and nuts    Beans (dry)           262  90 KG    actual
4  cereals and tubers  Maize (white)            67     KG    actual

   pricetype currency    price  usdprice
0  Wholesale      KES    16.13      0.22
1  Wholesale      KES  1480.00     20.58
2  Wholesale      KES    33.63      0.47
3  Wholesale      KES  3246.00     45.15
4     Retail      KES    17.00      0.24

In [3]:
# Print the column names to identify the variables in the dataset
print(data.columns)

Index(['date', 'admin1', 'admin2', 'market', 'market_id', 'latitude',
       'longitude', 'category', 'commodity', 'commodity_id', 'unit',
       'priceflag', 'pricetype', 'currency', 'price', 'usdprice'],
      dtype='str')

In [4]:
# Getting the general information about the dataset
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 18605 entries, 0 to 18604
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          18605 non-null  str
 1   admin1        18556 non-null  str
 2   admin2        18556 non-null  str
 3   market        18605 non-null  str
 4   market_id     18605 non-null  int64
 5   latitude      18556 non-null  float64
 6   longitude     18556 non-null  float64
 7   category      18605 non-null  str
 8   commodity     18605 non-null  str
 9   commodity_id  18605 non-null  int64
 10  unit          18605 non-null  str
 11  priceflag     18605 non-null  str
 12  pricetype     18605 non-null  str
 13  currency      18605 non-null  str
 14  price         18605 non-null  float64
 15  usdprice      18605 non-null  float64
dtypes: float64(4), int64(2), str(10)
memory usage: 2.3 MB
None

In [5]:
""" Deleting redundant columns
Renaming the columns 
Dropping duplicates
Cleaning individual columns
Remove the NoN values from the dataset
Check for some more Transformations"""

' Deleting redundant columns\nRenaming the columns \nDropping duplicates\nCleaning individual columns\nRemove the NoN values from the dataset\nCheck for some more Transformations'

In [6]:
# Filtering the dataset to include only the relevant columns for our analysis 
columns_to_keep = ["date", "admin1","admin2", "price", "commodity", "unit", "market", "category", "latitude", "longitude"]
columns_to_drop = ["market_id", "commodity_id", "currency", "priceflag", "pricetype", "usdprice"]
filtered_data = data[columns_to_keep]
print(filtered_data)
print(filtered_data)

            date         admin1   admin2    price        commodity   unit  \
0      1/15/2006          Coast  Mombasa    16.13            Maize     KG
1      1/15/2006          Coast  Mombasa  1480.00    Maize (white)  90 KG
2      1/15/2006          Coast  Mombasa    33.63            Beans     KG
3      1/15/2006          Coast  Mombasa  3246.00      Beans (dry)  90 KG
4      1/15/2006        Eastern    Kitui    17.00    Maize (white)     KG
...          ...            ...      ...      ...              ...    ...
18600  3/15/2026  North Eastern  Garissa   825.00      Meat (goat)     KG
18601  3/15/2026  North Eastern  Garissa    15.00             Salt  200 G
18602  3/15/2026  North Eastern  Garissa   120.00            Sugar     KG
18603  3/15/2026  North Eastern  Garissa   247.78  Oil (vegetable)      L
18604  3/15/2026  North Eastern  Garissa    10.00          Bananas   Unit

             market               category  latitude  longitude
0           Mombasa     cereals and tubers     -4.05      39.67
1           Mombasa     cereals and tubers     -4.05      39.67
2           Mombasa        pulses and nuts     -4.05      39.67
3           Mombasa        pulses and nuts     -4.05      39.67
4             Kitui     cereals and tubers     -1.37      38.02
...             ...                    ...       ...        ...
18600  IFO (Daadab)    meat, fish and eggs      0.11      40.32
18601  IFO (Daadab)     miscellaneous food      0.11      40.32
18602  IFO (Daadab)     miscellaneous food      0.11      40.32
18603  IFO (Daadab)           oil and fats      0.11      40.32
18604  IFO (Daadab)  vegetables and fruits      0.11      40.32

[18605 rows x 10 columns]
            date         admin1   admin2    price        commodity   unit  \
0      1/15/2006          Coast  Mombasa    16.13            Maize     KG
1      1/15/2006          Coast  Mombasa  1480.00    Maize (white)  90 KG
2      1/15/2006          Coast  Mombasa    33.63            Beans     KG
3      1/15/2006          Coast  Mombasa  3246.00      Beans (dry)  90 KG
4      1/15/2006        Eastern    Kitui    17.00    Maize (white)     KG
...          ...            ...      ...      ...              ...    ...
18600  3/15/2026  North Eastern  Garissa   825.00      Meat (goat)     KG
18601  3/15/2026  North Eastern  Garissa    15.00             Salt  200 G
18602  3/15/2026  North Eastern  Garissa   120.00            Sugar     KG
18603  3/15/2026  North Eastern  Garissa   247.78  Oil (vegetable)      L
18604  3/15/2026  North Eastern  Garissa    10.00          Bananas   Unit

             market               category  latitude  longitude
0           Mombasa     cereals and tubers     -4.05      39.67
1           Mombasa     cereals and tubers     -4.05      39.67
2           Mombasa        pulses and nuts     -4.05      39.67
3           Mombasa        pulses and nuts     -4.05      39.67
4             Kitui     cereals and tubers     -1.37      38.02
...             ...                    ...       ...        ...
18600  IFO (Daadab)    meat, fish and eggs      0.11      40.32
18601  IFO (Daadab)     miscellaneous food      0.11      40.32
18602  IFO (Daadab)     miscellaneous food      0.11      40.32
18603  IFO (Daadab)           oil and fats      0.11      40.32
18604  IFO (Daadab)  vegetables and fruits      0.11      40.32

[18605 rows x 10 columns]

In [7]:
print(filtered_data.head())

        date   admin1   admin2    price      commodity   unit   market  \
0  1/15/2006    Coast  Mombasa    16.13          Maize     KG  Mombasa
1  1/15/2006    Coast  Mombasa  1480.00  Maize (white)  90 KG  Mombasa
2  1/15/2006    Coast  Mombasa    33.63          Beans     KG  Mombasa
3  1/15/2006    Coast  Mombasa  3246.00    Beans (dry)  90 KG  Mombasa
4  1/15/2006  Eastern    Kitui    17.00  Maize (white)     KG    Kitui

             category  latitude  longitude
0  cereals and tubers     -4.05      39.67
1  cereals and tubers     -4.05      39.67
2     pulses and nuts     -4.05      39.67
3     pulses and nuts     -4.05      39.67
4  cereals and tubers     -1.37      38.02

In [8]:
# Drop the columns that are not needed for our analysis 
data.drop(columns=columns_to_drop, inplace=True, errors='ignore')

In [10]:
print(data.shape)

(18605, 10)

In [11]:
# Renaming the columns to more descriptive names
data.rename(columns={"admin1":"Region", "admin2":"County"}, inplace=True)

In [12]:
print(data)

            date         Region   County        market  latitude  longitude  \
0      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
1      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
2      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
3      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
4      1/15/2006        Eastern    Kitui         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18600  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18601  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18602  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18603  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18604  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price
0         cereals and tubers            Maize     KG    16.13
1         cereals and tubers    Maize (white)  90 KG  1480.00
2            pulses and nuts            Beans     KG    33.63
3            pulses and nuts      Beans (dry)  90 KG  3246.00
4         cereals and tubers    Maize (white)     KG    17.00
...                      ...              ...    ...      ...
18600    meat, fish and eggs      Meat (goat)     KG   825.00
18601     miscellaneous food             Salt  200 G    15.00
18602     miscellaneous food            Sugar     KG   120.00
18603           oil and fats  Oil (vegetable)      L   247.78
18604  vegetables and fruits          Bananas   Unit    10.00

[18605 rows x 10 columns]

In [13]:
new_column_names = []
for i in data.columns:
    new_column_names.append(i.upper())

print(new_column_names)

['DATE', 'REGION', 'COUNTY', 'MARKET', 'LATITUDE', 'LONGITUDE', 'CATEGORY', 'COMMODITY', 'UNIT', 'PRICE']

In [14]:
 # Creating a copy of the original dataset to keep the original data into account in case we need to refer to it later on 
# This allows modifications of the new dataframe without affecting or loosing the original data
new_dataframe_to_modify = data.copy()
# Renaming the columns to uppercase for better reading and consistenty in the new dataframe
new_dataframe_to_modify.columns = new_column_names
print(new_dataframe_to_modify)

            DATE         REGION   COUNTY        MARKET  LATITUDE  LONGITUDE  \
0      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
1      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
2      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
3      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
4      1/15/2006        Eastern    Kitui         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18600  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18601  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18602  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18603  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18604  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32

                    CATEGORY        COMMODITY   UNIT    PRICE
0         cereals and tubers            Maize     KG    16.13
1         cereals and tubers    Maize (white)  90 KG  1480.00
2            pulses and nuts            Beans     KG    33.63
3            pulses and nuts      Beans (dry)  90 KG  3246.00
4         cereals and tubers    Maize (white)     KG    17.00
...                      ...              ...    ...      ...
18600    meat, fish and eggs      Meat (goat)     KG   825.00
18601     miscellaneous food             Salt  200 G    15.00
18602     miscellaneous food            Sugar     KG   120.00
18603           oil and fats  Oil (vegetable)      L   247.78
18604  vegetables and fruits          Bananas   Unit    10.00

[18605 rows x 10 columns]

In [15]:
# Print the modified dataframe to verify the changes 
print(new_dataframe_to_modify.head())

        DATE   REGION   COUNTY   MARKET  LATITUDE  LONGITUDE  \
0  1/15/2006    Coast  Mombasa  Mombasa     -4.05      39.67
1  1/15/2006    Coast  Mombasa  Mombasa     -4.05      39.67
2  1/15/2006    Coast  Mombasa  Mombasa     -4.05      39.67
3  1/15/2006    Coast  Mombasa  Mombasa     -4.05      39.67
4  1/15/2006  Eastern    Kitui    Kitui     -1.37      38.02

             CATEGORY      COMMODITY   UNIT    PRICE
0  cereals and tubers          Maize     KG    16.13
1  cereals and tubers  Maize (white)  90 KG  1480.00
2     pulses and nuts          Beans     KG    33.63
3     pulses and nuts    Beans (dry)  90 KG  3246.00
4  cereals and tubers  Maize (white)     KG    17.00

In [16]:
# Checking for duplicates in the dataset 
new_dataframe_to_modify.duplicated().sum()

np.int64(0)

In [17]:
new_dataframe_to_modify.drop_duplicates()

,DATE,REGION,COUNTY,MARKET,LATITUDE,LONGITUDE,CATEGORY,COMMODITY,UNIT,PRICE
0,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.67,cereals and tubers,Maize,KG,16.13
1,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.67,cereals and tubers,Maize (white),90 KG,1480.00
2,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.67,pulses and nuts,Beans,KG,33.63
3,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.67,pulses and nuts,Beans (dry),90 KG,3246.00
4,1/15/2006,Eastern,Kitui,Kitui,-1.37,38.02,cereals and tubers,Maize (white),KG,17.00
...,...,...,...,...,...,...,...,...,...,...
18600,3/15/2026,North Eastern,Garissa,IFO (Daadab),0.11,40.32,"meat, fish and eggs",Meat (goat),KG,825.00
18601,3/15/2026,North Eastern,Garissa,IFO (Daadab),0.11,40.32,miscellaneous food,Salt,200 G,15.00
18602,3/15/2026,North Eastern,Garissa,IFO (Daadab),0.11,40.32,miscellaneous food,Sugar,KG,120.00
18603,3/15/2026,North Eastern,Garissa,IFO (Daadab),0.11,40.32,oil and fats,Oil (vegetable),L,247.78
18604,3/15/2026,North Eastern,Garissa,IFO (Daadab),0.11,40.32,vegetables and fruits,Bananas,Unit,10.00

In [18]:
# Remove the NoN values from the dataset
data.isna().sum()

date          0
Region       49
County       49
market        0
latitude     49
longitude    49
category      0
commodity     0
unit          0
price         0
dtype: int64

In [19]:
data.dropna(inplace=True)

In [20]:
data.isna().sum()

date         0
Region       0
County       0
market       0
latitude     0
longitude    0
category     0
commodity    0
unit         0
price        0
dtype: int64

In [21]:
# Cleaning individual columns
print(data)

            date         Region   County        market  latitude  longitude  \
0      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
1      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
2      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
3      1/15/2006          Coast  Mombasa       Mombasa     -4.05      39.67
4      1/15/2006        Eastern    Kitui         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18600  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18601  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18602  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18603  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32
18604  3/15/2026  North Eastern  Garissa  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price
0         cereals and tubers            Maize     KG    16.13
1         cereals and tubers    Maize (white)  90 KG  1480.00
2            pulses and nuts            Beans     KG    33.63
3            pulses and nuts      Beans (dry)  90 KG  3246.00
4         cereals and tubers    Maize (white)     KG    17.00
...                      ...              ...    ...      ...
18600    meat, fish and eggs      Meat (goat)     KG   825.00
18601     miscellaneous food             Salt  200 G    15.00
18602     miscellaneous food            Sugar     KG   120.00
18603           oil and fats  Oil (vegetable)      L   247.78
18604  vegetables and fruits          Bananas   Unit    10.00

[18556 rows x 10 columns]

In [22]:
county_positions = [i for i, col in enumerate(data.columns) if col == "County"]
for pos in county_positions:
	data.iloc[:, pos] = data.iloc[:, pos].astype(str).str.upper()
# This converts all County columns to uppercase

In [23]:
# modyfying the dataset to reflect the changes in the county column
data["County"] = data["County"].astype(str).str.upper()

In [24]:
print(data)

            date         Region   County        market  latitude  longitude  \
0      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
1      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
2      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
3      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
4      1/15/2006        Eastern    KITUI         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18600  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18601  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18602  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18603  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18604  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price
0         cereals and tubers            Maize     KG    16.13
1         cereals and tubers    Maize (white)  90 KG  1480.00
2            pulses and nuts            Beans     KG    33.63
3            pulses and nuts      Beans (dry)  90 KG  3246.00
4         cereals and tubers    Maize (white)     KG    17.00
...                      ...              ...    ...      ...
18600    meat, fish and eggs      Meat (goat)     KG   825.00
18601     miscellaneous food             Salt  200 G    15.00
18602     miscellaneous food            Sugar     KG   120.00
18603           oil and fats  Oil (vegetable)      L   247.78
18604  vegetables and fruits          Bananas   Unit    10.00

[18556 rows x 10 columns]

In [27]:
# Checking for more transformations
data.to_csv("Cleaned_Data.csv")

In [28]:
pd.read_csv("Cleaned_Data.csv")
# reads the ccleaned data that was modified

,Unnamed: 0,date,Region,County,market,latitude,longitude,category,commodity,unit,price
0,0,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,cereals and tubers,Maize,KG,16.13
1,1,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,cereals and tubers,Maize (white),90 KG,1480.00
2,2,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,pulses and nuts,Beans,KG,33.63
3,3,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,pulses and nuts,Beans (dry),90 KG,3246.00
4,4,1/15/2006,Eastern,KITUI,Kitui,-1.37,38.02,cereals and tubers,Maize (white),KG,17.00
...,...,...,...,...,...,...,...,...,...,...,...
18551,18600,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,"meat, fish and eggs",Meat (goat),KG,825.00
18552,18601,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,miscellaneous food,Salt,200 G,15.00
18553,18602,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,miscellaneous food,Sugar,KG,120.00
18554,18603,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,oil and fats,Oil (vegetable),L,247.78
18555,18604,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,vegetables and fruits,Bananas,Unit,10.00

In [30]:
data.to_csv("Cleaned_Data.csv",index = False)
# This removes the index column

In [33]:
# Check the current columns in the dataframe
print(data.columns)

# If 'Index' is not a column, this drop will fail. Based on the dataframe info, 'Index' is not present.
# If you intended to remove the index (row labels), use reset_index instead:
data.reset_index(drop=True, inplace=True)

Index(['date', 'Region', 'County', 'market', 'latitude', 'longitude',
       'category', 'commodity', 'unit', 'price'],
      dtype='str')

In [34]:
print(data)

            date         Region   County        market  latitude  longitude  \
0      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
1      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
2      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
3      1/15/2006          Coast  MOMBASA       Mombasa     -4.05      39.67
4      1/15/2006        Eastern    KITUI         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18551  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18552  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18553  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18554  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18555  3/15/2026  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price
0         cereals and tubers            Maize     KG    16.13
1         cereals and tubers    Maize (white)  90 KG  1480.00
2            pulses and nuts            Beans     KG    33.63
3            pulses and nuts      Beans (dry)  90 KG  3246.00
4         cereals and tubers    Maize (white)     KG    17.00
...                      ...              ...    ...      ...
18551    meat, fish and eggs      Meat (goat)     KG   825.00
18552     miscellaneous food             Salt  200 G    15.00
18553     miscellaneous food            Sugar     KG   120.00
18554           oil and fats  Oil (vegetable)      L   247.78
18555  vegetables and fruits          Bananas   Unit    10.00

[18556 rows x 10 columns]

In [36]:
pd.read_csv("Cleaned_Data.csv")

,date,Region,County,market,latitude,longitude,category,commodity,unit,price
0,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,cereals and tubers,Maize,KG,16.13
1,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,cereals and tubers,Maize (white),90 KG,1480.00
2,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,pulses and nuts,Beans,KG,33.63
3,1/15/2006,Coast,MOMBASA,Mombasa,-4.05,39.67,pulses and nuts,Beans (dry),90 KG,3246.00
4,1/15/2006,Eastern,KITUI,Kitui,-1.37,38.02,cereals and tubers,Maize (white),KG,17.00
...,...,...,...,...,...,...,...,...,...,...
18551,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,"meat, fish and eggs",Meat (goat),KG,825.00
18552,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,miscellaneous food,Salt,200 G,15.00
18553,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,miscellaneous food,Sugar,KG,120.00
18554,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,oil and fats,Oil (vegetable),L,247.78
18555,3/15/2026,North Eastern,GARISSA,IFO (Daadab),0.11,40.32,vegetables and fruits,Bananas,Unit,10.00

In [38]:
# Converting the date column to datetime format 
data["date"] = pd.to_datetime(data["date"], errors="coerce")

In [41]:
print(data)

            date         Region   County        market  latitude  longitude  \
0     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
1     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
2     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
3     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
4     2006-01-15        Eastern    KITUI         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18551 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18552 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18553 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18554 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18555 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price    Year
0         cereals and tubers            Maize     KG    16.13  2006.0
1         cereals and tubers    Maize (white)  90 KG  1480.00  2006.0
2            pulses and nuts            Beans     KG    33.63  2006.0
3            pulses and nuts      Beans (dry)  90 KG  3246.00  2006.0
4         cereals and tubers    Maize (white)     KG    17.00  2006.0
...                      ...              ...    ...      ...     ...
18551    meat, fish and eggs      Meat (goat)     KG   825.00  2026.0
18552     miscellaneous food             Salt  200 G    15.00  2026.0
18553     miscellaneous food            Sugar     KG   120.00  2026.0
18554           oil and fats  Oil (vegetable)      L   247.78  2026.0
18555  vegetables and fruits          Bananas   Unit    10.00  2026.0

[18556 rows x 11 columns]

In [39]:
# Creating a new column for the year to make grouping easier
data["Year"] = data["date"].dt.year
# Now you can see how many records you have per year

In [40]:
print(data["Year"].value_counts())

Year
2024.0    4402
2021.0    3930
2023.0    2352
2025.0    1798
2022.0    1360
2018.0     406
2017.0     392
2016.0     386
2019.0     372
2015.0     361
2011.0     297
2014.0     292
2010.0     287
2008.0     283
2009.0     279
2013.0     275
2012.0     271
2006.0     266
2007.0     250
2020.0     201
2026.0      95
Name: count, dtype: int64

In [42]:
print(data)

            date         Region   County        market  latitude  longitude  \
0     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
1     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
2     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
3     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
4     2006-01-15        Eastern    KITUI         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18551 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18552 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18553 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18554 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18555 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price    Year
0         cereals and tubers            Maize     KG    16.13  2006.0
1         cereals and tubers    Maize (white)  90 KG  1480.00  2006.0
2            pulses and nuts            Beans     KG    33.63  2006.0
3            pulses and nuts      Beans (dry)  90 KG  3246.00  2006.0
4         cereals and tubers    Maize (white)     KG    17.00  2006.0
...                      ...              ...    ...      ...     ...
18551    meat, fish and eggs      Meat (goat)     KG   825.00  2026.0
18552     miscellaneous food             Salt  200 G    15.00  2026.0
18553     miscellaneous food            Sugar     KG   120.00  2026.0
18554           oil and fats  Oil (vegetable)      L   247.78  2026.0
18555  vegetables and fruits          Bananas   Unit    10.00  2026.0

[18556 rows x 11 columns]

In [43]:
# Creating a Week and Month column so that you can tell what specific day the sales peak
data["Week"]=data["date"].dt.day_name()
data["Month"]=data["date"].dt.month_name()

In [44]:
print(data)

            date         Region   County        market  latitude  longitude  \
0     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
1     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
2     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
3     2006-01-15          Coast  MOMBASA       Mombasa     -4.05      39.67
4     2006-01-15        Eastern    KITUI         Kitui     -1.37      38.02
...          ...            ...      ...           ...       ...        ...
18551 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18552 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18553 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18554 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32
18555 2026-03-15  North Eastern  GARISSA  IFO (Daadab)      0.11      40.32

                    category        commodity   unit    price    Year    Week  \
0         cereals and tubers            Maize     KG    16.13  2006.0  Sunday
1         cereals and tubers    Maize (white)  90 KG  1480.00  2006.0  Sunday
2            pulses and nuts            Beans     KG    33.63  2006.0  Sunday
3            pulses and nuts      Beans (dry)  90 KG  3246.00  2006.0  Sunday
4         cereals and tubers    Maize (white)     KG    17.00  2006.0  Sunday
...                      ...              ...    ...      ...     ...     ...
18551    meat, fish and eggs      Meat (goat)     KG   825.00  2026.0  Sunday
18552     miscellaneous food             Salt  200 G    15.00  2026.0  Sunday
18553     miscellaneous food            Sugar     KG   120.00  2026.0  Sunday
18554           oil and fats  Oil (vegetable)      L   247.78  2026.0  Sunday
18555  vegetables and fruits          Bananas   Unit    10.00  2026.0  Sunday

         Month
0      January
1      January
2      January
3      January
4      January
...        ...
18551    March
18552    March
18553    March
18554    March
18555    March

[18556 rows x 13 columns]